sudo: false
language: node_js
node_js:
  - node
  - '6'
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: 39c710513d49b85f9cd9360fae42a7019691b96d639a5e95caf3116a09f455f6
notifications:
  email: false
  slack:
    rooms:
      secure: A45tmvXAxLq82nbr8vazo30OpiDo1UMKkmMzmCjUfGjJ7dcAspCmOZOg/qpj5Pe/gKI5uGNq7/cF+JWMXVxC+dirndl+eo1WQrDcR5IzAUe0Zku43SoK19hFYpZy4zSL6z4bAL03Id4Sst0wSH0tnAyvagPASlaUAH4EM//fZ1I=
